
backend:
  name: github
  repo: GhostRicity/3-way
  branch: master
  use_graphql: true

media_folder: static/img
public_folder: /img

collections:
  - label: Post
    name: portfolio
    folder: posts
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: thumbnail, label: thumbnail, widget: image }
      - { name: description, label: Description }
      - { name: url, labe: url, widget: string }
